version: "2"

services:
  idaw-node:
    image: "node:20.11.1-bookworm"
    container_name: idaw-node
    user: "node"
    working_dir: /home/node/app
    entrypoint: ["tail", "-f", "/dev/null"]
    #entrypoint: ["node", "src/index.js"]
    #entrypoint: ["npx", "nodemon", "-L", "--watch", "src", "-e", "js,mjs,cjs,json,ejs", "src/index.js"]
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    expose:
      - "9080"
    ports:
      - "9080:9080"

  idaw-mongo:
    image: mongodb/mongodb-community-server:8.0.0-ubuntu2204
    container_name: idaw-mongo
    ports:
      - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=root
      - MONGODB_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=test
      - MONGODB_INITDB_DATABASE=test
    volumes:
      - ./data/db:/data/db
      - ./data/configdb:/data/configdb
